// code.ts

// 変数名をCSSカスタムプロパティのフォーマット（ケバブケース）に正規化
function normalizeName(name: string): string {
  const sanitized = name
    .replace(/[^a-zA-Z0-9_-]/g, "-") // 英数字、アンダースコア、ハイフン以外（カンマやドットなど）をすべてハイフンに置換
    .replace(/-+/g, "-") // 連続するハイフンを1つにまとめる（例: --- を - に）
    .replace(/^-+|-+$/g, "") // 先頭と末尾のハイフンを削除
    .toLowerCase(); // すべて小文字にする

  return `--${sanitized}`;
}

// FigmaのRGBAオブジェクトをCSSのrgb()文字列に変換
function rgbaToCss(rgba: RGBA): string {
  const r = Math.round(rgba.r * 255);
  const g = Math.round(rgba.g * 255);
  const b = Math.round(rgba.b * 255);
  return rgba.a === 1
    ? `rgb(${r} ${g} ${b})`
    : `rgb(${r} ${g} ${b} / ${rgba.a})`;
}

// Type Guard: 値がVariableAlias（エイリアス）かどうかを判定
function isVariableAlias(value: VariableValue): value is VariableAlias {
  return (
    typeof value === "object" &&
    value !== null &&
    "type" in value &&
    value.type === "VARIABLE_ALIAS"
  );
}

// 型に応じてFigmaの値をCSSのプロパティ値にフォーマット
function formatValue(
  value: VariableValue,
  type: VariableResolvedDataType,
  name: string,
  variableMap: Map<string, Variable>,
): string {
  // エイリアス解決
  if (isVariableAlias(value)) {
    const targetVar = variableMap.get(value.id);
    return targetVar
      ? `var(${normalizeName(targetVar.name)})`
      : "/* unresolved alias */";
  }

  // プリミティブ値の変換
  switch (type) {
    case "COLOR":
      return rgbaToCss(value as RGBA);

    case "FLOAT":
      const lowerName = name.toLowerCase();
      const numValue = value as number;
      // 名称による単位の推論
      if (lowerName.includes("spacing") || lowerName.includes("radius")) {
        return `${numValue / 16}rem`;
      } else if (lowerName.includes("opacity")) {
        return String(numValue);
      }
      return `${numValue}px`;

    case "STRING":
      return `"${value}"`;

    case "BOOLEAN":
      return value ? "1" : "0";

    default:
      return String(value);
  }
}

// メインの非同期処理
async function generateCSS(): Promise<void> {
  // UIの表示
  figma.showUI(__html__, { width: 450, height: 500 });

  try {
    // ローカルのコレクションとバリアブルを全取得
    const collections =
      await figma.variables.getLocalVariableCollectionsAsync();
    const variables = await figma.variables.getLocalVariablesAsync();

    // エイリアス解決のための高速検索マップ
    const variableMap = new Map<string, Variable>();
    variables.forEach((v) => variableMap.set(v.id, v));

    let cssOutput = `/* Generated by Custom Figma Variables Exporter */\n\n`;

    for (const collection of collections) {
      for (const mode of collection.modes) {
        const modeName = mode.name.toLowerCase();
        // デフォルトモード、または名前に'light'が含まれる場合は :root に出力
        const isDefault =
          collection.defaultModeId === mode.modeId || modeName === "light";
        const selector = isDefault ? ":root" : `[data-theme="${modeName}"]`;

        cssOutput += `/* Collection: ${collection.name}, Mode: ${mode.name} */\n`;
        cssOutput += `${selector} {\n`;

        for (const variable of variables) {
          // 対象コレクション以外の変数、または公開除外変数をスキップ
          if (variable.variableCollectionId !== collection.id) continue;
          if (variable.hiddenFromPublishing || variable.remote) continue;

          const value = variable.valuesByMode[mode.modeId];
          if (value !== undefined) {
            const cssName = normalizeName(variable.name);
            const cssValue = formatValue(
              value,
              variable.resolvedType,
              variable.name,
              variableMap,
            );

            // Descriptionが存在すればCSSコメントとして出力
            if (variable.description) {
              cssOutput += `  /* ${variable.description.replace(/\n/g, " ")} */\n`;
            }
            cssOutput += `  ${cssName}: ${cssValue};\n`;
          }
        }
        cssOutput += `}\n\n`;
      }
    }

    // UIへ生成データを送信
    figma.ui.postMessage({ type: "export-css", data: cssOutput });
  } catch (error) {
    console.error("Error generating CSS:", error);
    figma.notify(
      "CSSの生成中にエラーが発生しました。コンソールを確認してください。",
    );
  }
}

// 実行
generateCSS();
