// --- ユーティリティ関数 ---
function normalizeName(name: string): string {
  const sanitized = name
    .replace(/[^a-zA-Z0-9_-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `--${sanitized}`;
}

function toTailwindName(name: string, type: VariableResolvedDataType): string {
  let sanitized = name
    .replace(/[^a-zA-Z0-9_-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  if (type === "COLOR") {
    sanitized = sanitized.replace(/^colors?-/, "");
    return `--color-${sanitized}`;
  }
  if (type === "FLOAT") {
    if (
      sanitized.includes("spacing") ||
      sanitized.includes("gap") ||
      sanitized.includes("padding")
    ) {
      sanitized = sanitized.replace(/^(spacing|gap|padding)s?-/, "");
      return `--spacing-${sanitized}`;
    }
    if (sanitized.includes("radius") || sanitized.includes("rounded")) {
      sanitized = sanitized.replace(/^(radius|rounded|radiuses)-/, "");
      return `--radius-${sanitized}`;
    }
    if (sanitized.includes("text") || sanitized.includes("font-size")) {
      sanitized = sanitized.replace(/^(text|font-size)s?-/, "");
      return `--text-${sanitized}`;
    }
  }
  if (type === "STRING" && sanitized.includes("font")) {
    sanitized = sanitized.replace(/^fonts?-/, "");
    return `--font-${sanitized}`;
  }
  return `--${sanitized}`;
}

function rgbaToCss(rgba: RGBA): string {
  const r = Math.round(rgba.r * 255);
  const g = Math.round(rgba.g * 255);
  const b = Math.round(rgba.b * 255);
  return rgba.a === 1
    ? `rgb(${r} ${g} ${b})`
    : `rgb(${r} ${g} ${b} / ${rgba.a})`;
}

function isVariableAlias(value: VariableValue): value is VariableAlias {
  return (
    typeof value === "object" &&
    value !== null &&
    "type" in value &&
    value.type === "VARIABLE_ALIAS"
  );
}

function formatValue(
  value: VariableValue,
  type: VariableResolvedDataType,
  name: string,
  format: "standard" | "tailwind",
  variableMap: Map<string, Variable>,
): string {
  if (isVariableAlias(value)) {
    const targetVar = variableMap.get(value.id);
    if (!targetVar) return "/* unresolved alias */";
    const targetName =
      format === "tailwind"
        ? toTailwindName(targetVar.name, targetVar.resolvedType)
        : normalizeName(targetVar.name);
    return `var(${targetName})`;
  }
  switch (type) {
    case "COLOR":
      return rgbaToCss(value as RGBA);
    case "FLOAT":
      const lowerName = name.toLowerCase();
      const numValue = value as number;
      if (
        lowerName.includes("spacing") ||
        lowerName.includes("gap") ||
        lowerName.includes("radius")
      )
        return `${numValue / 16}rem`;
      else if (lowerName.includes("opacity")) return String(numValue);
      return `${numValue}px`;
    case "STRING":
      return `"${value}"`;
    case "BOOLEAN":
      return value ? "1" : "0";
    default:
      return String(value);
  }
}

// --- メインプロセス ---
figma.showUI(__html__, { width: 500, height: 650 });

async function generateAndSend(format: "standard" | "tailwind") {
  try {
    const collections =
      await figma.variables.getLocalVariableCollectionsAsync();
    const variables = await figma.variables.getLocalVariablesAsync();
    const variableMap = new Map<string, Variable>();
    variables.forEach((v) => variableMap.set(v.id, v));

    let cssOutput = `/* Generated by Figma Variables Exporter */\n`;
    if (format === "tailwind") {
      cssOutput += `/* Tailwind CSS v4 Theme Format */\n`;
      cssOutput += `@import "tailwindcss";\n\n`;
    } else {
      cssOutput += `/* Standard CSS Variables */\n\n`;
    }

    for (const collection of collections) {
      for (const mode of collection.modes) {
        const modeName = mode.name.toLowerCase();
        const isDefault =
          collection.defaultModeId === mode.modeId || modeName === "light";

        let selector =
          format === "tailwind"
            ? isDefault
              ? "@theme"
              : `[data-theme="${modeName}"]`
            : isDefault
              ? ":root"
              : `[data-theme="${modeName}"]`;

        cssOutput += `/* Collection: ${collection.name}, Mode: ${mode.name} */\n`;
        cssOutput += `${selector} {\n`;

        for (const variable of variables) {
          if (variable.variableCollectionId !== collection.id) continue;
          if (variable.hiddenFromPublishing || variable.remote) continue;

          const value = variable.valuesByMode[mode.modeId];
          if (value !== undefined) {
            const cssName =
              format === "tailwind"
                ? toTailwindName(variable.name, variable.resolvedType)
                : normalizeName(variable.name);
            const cssValue = formatValue(
              value,
              variable.resolvedType,
              variable.name,
              format,
              variableMap,
            );
            if (variable.description)
              cssOutput += `  /* ${variable.description.replace(/\n/g, " ")} */\n`;
            cssOutput += `  ${cssName}: ${cssValue};\n`;
          }
        }
        cssOutput += `}\n\n`;
      }
    }
    figma.ui.postMessage({ type: "export-css", data: cssOutput });
  } catch (error) {
    console.error("生成エラー:", error);
    figma.ui.postMessage({
      type: "export-css",
      data: "エラーが発生しました。コンソールを確認してください。",
    });
  }
}

// プラグイン起動時の初回実行
generateAndSend("tailwind");

// UIからのフォーマット変更リクエストを受信
figma.ui.onmessage = (msg) => {
  if (msg.type === "generate") {
    generateAndSend(msg.format);
  }
};
